- name: Tap a hcp Homebrew repository, state present
  become: false
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: Install hcp
  become: false
  community.general.homebrew:
    name: hcp
    state: present
