- name: HCP exists
  ansible.builtin.stat:
    path: /usr/local/bin/hcp
  register: hcp_stat


- name: Install hcp
  when: not hcp_stat.stat.exists
  become: true
  block:
    - name: Determine architecture
      set_fact:
        hcp_arch: "amd64"
      when: ansible_architecture == "x86_64"

    - name: Determine architecture
      set_fact:
        hcp_arch: "arm64"
      when: ansible_architecture == "aarch64"

    - name: Download hcp
      get_url:
        url: "https://releases.hashicorp.com/hcp/0.8.0/hcp_0.8.0_linux_{{ hcp_arch }}.zip"
        dest: /tmp/hcp.zip

    - name: Extract eza
      unarchive:
        src: /tmp/hcp.zip
        dest: /tmp
        remote_src: yes

    - name: Move eza to /usr/local/bin
      copy:
        src: /tmp/hcp
        dest: /usr/local/bin/hcp
        remote_src: yes
        owner: root
        group: root
        mode: "0755"
