- name: Install CLI packages (Suse)
  community.general.zypper:
    name: "{{ cli_common_packages_suse }}"
    state: present

- name: Add atuin config to end of .zshrc
  become: false
  blockinfile:
    path: "/home/{{ original_user }}/.zshrc"
    block: |
      eval "$(atuin init zsh)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Atuin CONFIG"
    insertafter: EOF
    create: false

- name: Add zoxide config to end of .zshrc
  become: false
  blockinfile:
    path: "/home/{{ original_user }}/.zshrc"
    block: |
      eval "$(zoxide init zsh)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Zoxide CONFIG"
    insertafter: EOF
    create: false
