---
common_packages:
  - git
  - zsh
  - curl
  - wget
  - vim
  - fzf
  - htop
  - jq
  - mosh

common_packages_ubuntu:
  - apt-transport-https
  - bat

common_packages_suse:
  - bat

oh_my_zsh_plugins:
  - git
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - you-should-use
  - aliases
