---
cli_common_packages_ubuntu:
  - bat
  - ripgrep
  - fd-find
  - duf
  - ncdu
  - btop
  - hexyl
  - nnn
  - direnv
  - magic-wormhole
  - hyperfine
  - pv
  - rclone
  - restic

cli_common_packages_suse:
  - atuin
  - zoxide
  - fzf
  - htop
  - jq
  - eza
  - mosh
  - git-delta
  - fd
  - duf
  - ncdu
  - btop
  - bottom
  - sd
  - hexyl
  - nnn
  - broot
  - direnv
  - magic-wormhole.rs
  - hyperfine
  - httpie
  - lnav
  - glow
  - yq
  - fx
  - jless
  - pv
  - rclone
  - restic
  - onefetch

cli_common_packages_macosx:
  - gh
  - ghostty
  - "atuin"
  - "zoxide"
  - "bat"
  - "fzf"
  - "htop"
  - "jq"
  - "tre-command"
  - "md5sha1sum"
  - "ripgrep"
  - "eza"
  - "mosh"
  - "delta"
  - "fd"
  - "duf"
  - "dust"
  - "ncdu"
  - "btop"
  - "bottom"
  - "tldr"
  - "sd"
  - "hexyl"
  - "nnn"
  - "broot"
  - "direnv"
  - "croc"
  - "magic-wormhole"
  - "hyperfine"
  - "httpie"
  - "xh"
  - "thefuck"
  - "lnav"
  - "glow"
  - "yq"
  - "fx"
  - "jless"
  - "pv"
  - "entr"
  - "rclone"
  - "restic"
  - "diskonaut"
  - "onefetch"
  - "cheat"
  - "navi"
  - "yadm"
  - "yazi"